language: python
python:
    - "2.7"

before_script:
    cd co2meter

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run

